baseURL = 'https://www.gameful.dev'
languageCode = 'en-gb'
title = 'Gameful'
theme = 'gameful'

[contentTypes]
    [contentTypes.projects]
        name = "Projects"
        singular = "Project"
        plural = "Projects"
        layout = "project"

[menu]
    [[menu.main]]
        name = "About"
        url = "/about/"
        weight = 2
    [[menu.main]]
        name = "Projects"
        url = "/projects/"
        weight = 3
    [[menu.main]]
        name = "News"
        url = "/posts/"
        weight = 4
    [[menu.main]]
        name = "Contact"
        url = "/contact/"
        weight = 5

    [[menu.social]]
        name = "Twitter"
        pre = "twitter"
        url = "https://twitter.com/gamefuldev"
        weight = 1
    [[menu.social]]
        name = "YouTube"
        pre = "youtube"
        url = "https://www.youtube.com/@gamefuldev"
        weight = 1
    [[menu.social]]
        name = "Steam"
        pre = "shopping-cart"
        url = "https://store.steampowered.com/app/2265750?utm_source=gameful"
        weight = 1